---
- hosts: myhosts
  name: Set boot mode to Legacy BIOS and reboot
  gather_facts: False

  tasks:

  - name: Set BootMode to Legacy BIOS
    local_action: >
       redfish category=System command=SetBiosAttributes
       user={{user}} password={{password}} baseuri={{baseuri}}
       bios_attr_name=BootMode bios_attr_value=Bios
    ignore_errors: yes

  - name: Create config job - reboot
    local_action: >
      redfish category=System command=CreateBiosConfigJob baseuri={{baseuri}}
      user={{user}} password={{password}}
    ignore_errors: yes
