---
- hosts: myhosts
  connection: local
  name: Get disk inventory
  gather_facts: False

  vars:
    datatype: DiskInventory

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get disk inventory
    redfish_facts:
      category: Systems
      command: GetDiskInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
