---
  - name: Define timestamp
    set_fact: timestamp="{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

  - name: Define file to place results
    set_fact: template={{rootdir}}/{{host}}/{{host}}_{{type}}_{{timestamp}}

  - name: Create dropoff directory for host
    file:
      path: "{{ rootdir }}/{{ host }}"
      state: directory
