---
- hosts: myhosts
  name: Power Supply (PSU) Inventory
  gather_facts: False

  tasks:

  # Not supported in 12G servers

  - name: Define output file
    include: set_output_file.yml type=PsuInventory

  - name: Get PSU Inventory
    local_action: >
       redfish category=Inventory command=GetPsuInventory baseuri={{baseuri}}
       user={{user}} password={{password}}
    register: result
    ignore_errors: yes

  - name: Copy information to output file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
