---
- hosts: myhosts
  name: System Inventory
  gather_facts: False

  tasks:

  - name: Define output file
    include: set_output_file.yml type=SystemInventory

  - name: Getting system inventory
    local_action: >
       redfish category=Inventory command=GetSystemInventory baseuri={{baseuri}}
       login={{login}} password={{password}}
    register: result

  - name: Copy results to output file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
