---
- hosts: myhosts
  name: Device Firmware Inventory
  gather_facts: False

  tasks:

  - name: Set output file
    include_tasks: set_output_file.yml type=FirmwareInventory

  - name: Get Firmware Inventory
    local_action: >
       redfish category=Update command=GetFirmwareInventory baseuri={{baseuri}}
       user={{user}} password={{password}}
    register: result
    ignore_errors: yes

  - name: Copy inventory to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
